// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file eProsimaClockType.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "eProsimaClockType.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

eProsimaClock::eProsimaClock()
{
    // m_time com.eprosima.idl.parser.typecode.PrimitiveTypeCode@6f7fd0e6
    m_time = 0;

}

eProsimaClock::~eProsimaClock()
{
}

eProsimaClock::eProsimaClock(const eProsimaClock &x)
{
    m_time = x.m_time;
}

eProsimaClock::eProsimaClock(eProsimaClock &&x)
{
    m_time = x.m_time;
}

eProsimaClock& eProsimaClock::operator=(const eProsimaClock &x)
{

    m_time = x.m_time;

    return *this;
}

eProsimaClock& eProsimaClock::operator=(eProsimaClock &&x)
{

    m_time = x.m_time;

    return *this;
}

size_t eProsimaClock::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    return current_alignment - initial_alignment;
}

size_t eProsimaClock::getCdrSerializedSize(const eProsimaClock& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    return current_alignment - initial_alignment;
}

void eProsimaClock::serialize(eprosima::fastcdr::Cdr &scdr) const
{

    scdr << m_time;
}

void eProsimaClock::deserialize(eprosima::fastcdr::Cdr &dcdr)
{

    dcdr >> m_time;
}

/*!
 * @brief This function sets a value in member time
 * @param _time New value for member time
 */
void eProsimaClock::time(int64_t _time)
{
m_time = _time;
}

/*!
 * @brief This function returns the value of member time
 * @return Value of member time
 */
int64_t eProsimaClock::time() const
{
    return m_time;
}

/*!
 * @brief This function returns a reference to member time
 * @return Reference to member time
 */
int64_t& eProsimaClock::time()
{
    return m_time;
}


size_t eProsimaClock::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;



    return current_align;
}

bool eProsimaClock::isKeyDefined()
{
   return false;
}

void eProsimaClock::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
	(void) scdr;
	 
}
